:queues:
  - brainstormer_online_development_default
  - brainstormer_online_production_default
  - brainstormer_online_production_ahoy
  - brainstormer_online_production_mailers
  - brainstormer_online_production_active_storage_purge
  - brainstormer_online_production_scheduler
:scheduler:
  :schedule:
    check_free_trial_criteria_job:
      queue: brainstormer_online_production_scheduler
      cron: '0 25 12 * * *'   # runs every day at 12:25 UTC time
      class: CheckFreeTrialCriteriaJob
    delete_ahoy_visit_ips:
      queue: brainstormer_online_production_scheduler
      cron: '0 0 0 1 * *'   # 
      class: DeleteAhoyVisitIps