:queues:
  - brainstormer_online_development_default
  - brainstormer_online_production_default
  - brainstormer_online_production_ahoy
  - brainstormer_online_production_mailers
  - brainstormer_online_production_active_storage_purge
  - brainstormer_online_production_scheduler
:scheduler:
  :schedule:
    check_free_trial_criteria_job:
      queue: brainstormer_online_production_scheduler
      cron: '25 15 * * * *'   # runs every day at 3:25 pm UTC time
      class: CheckFreeTrialCriteriaJob